### ISSUE TITLE
Make Opensource

### ISSUE THREAD

**Issue by FlorianWendelborn** [FlorianWendelborn/iotick#2]
- [x] @dodekeract's approval
- [x] @igeligel's approval
- [x] @rychoo2's approval
- [x] withdraw IOTA from demo accounts
- [x] clean up code
- [x] add MIT license
- [x] publish repository

---

@rychoo2, @igeligel, please tick the checkboxes if you approve.

**Comment by FlorianWendelborn** [comment]
@rychoo2 do you have any reason not to agree? Anything we can fix?

**Comment by rychoo2** [comment]
all good, sorry for the delay :)
